# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "TestKit"

  lane :build_lane do |options|
      scheme = options[:scheme]
      build_app(
        scheme: scheme,
        skip_package_ipa: true,
        skip_archive: true,
        silent: true, # less logs
        derived_data_path: "build/DerivedData",
        sdk: "iphonesimulator",
        clean: true
    )
  end

  lane :ui_tests do |options|
    scheme = options[:scheme]

    scan(
      scheme: scheme,
      clean: false,
      derived_data_path: "build/DerivedData",
      only_testing: scheme,
      output_directory: "tests_output",
      result_bundle: true,
      skip_build: true,
      sdk: "iphonesimulator"
    )
  end
end
