# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#
# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane
default_platform(:ios)

platform :ios do
  desc "TestKit"

  lane :build_framework do |options|
      scheme = options[:scheme]
      build_app(
        skip_package_ipa: true,
        skip_archive: true,
        silent: true, # less logs
        clean: true,
        result_bundle: true,
        scheme: "TestKit",
        derived_data_path: "./output/DerivedData",
        sdk: "iphonesimulator",
        
    )
  end

  lane :ui_test_plan do |options|
    testplan = options[:testplan]
    scan(
      testplan: testplan,
      clean: true,
      result_bundle: true,
      skip_build: true,
      parallel_testing: true,
      only_testing: "TestKitDemoUITests",
      scheme: "TestKitDemo",
      output_directory: "./output/tests",
      sdk: "iphonesimulator",
      derived_data_path: "./output/DerivedData"
    )
  end
end
