# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "TestKit"

  lane :build do |options|
      scheme = options[:scheme]
      build_app(
        scheme: scheme,
        skip_package_ipa: true,
        skip_archive: true,
        skip_codesigning: true,
        silent: true, # less logs
        clean: true,
        sdk: "iphonesimulator",
        output_directory: "output/build",
        derived_data_path: "output/build/DerivedData"
    )
  end

  lane :buildForTesting do |options|
    scheme = options[:scheme]
    device = options[:device]
    testplan = options[:testplan]
    scan(
      scheme: scheme,
      only_testing: scheme,
      clean: false,
      result_bundle: true,
      skip_build: true,
      parallel_testing: true,
      build_for_testing: true,
      sdk: "iphonesimulator",
      device: "iPhone 11",
      derived_data_path: "output/build/DerivedData",
      output_directory: "output/tests",
      testplan: testplan
    )
  end

  lane :ui_tests do |options|
    scheme = options[:scheme]
    device = options[:device]
    testplan = options[:testplan]
    scan(
      scheme: scheme,
      only_testing: scheme,
      clean: false,
      result_bundle: true,
      skip_build: true,
      parallel_testing: true,
      test_without_building: true,
      sdk: "iphonesimulator",
      device: "iPhone 11",
      derived_data_path: "output/build/DerivedData",
      output_directory: "output/tests",
      testplan: testplan
    )
  end
end
