name: pr_workflow

on:
  pull_request:
    branches:
      - main

jobs:
  build_framework_for_testing:
    runs-on: macos-latest
    name: build_framework_for_testing
    strategy:
      fail-fast: false
    steps:
      - name: Cancel previous jobs
        uses: styfle/cancel-workflow-action@0.6.0
        with:
          access_token: ${{ github.token }}
      - name: Git - Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          ruby-version: 2.6
      - run: bundle install
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: "12.5.1"
      - name: Clean fastlane output
        run: bundle exec fastlane clean
      - name: Build
        run: bundle exec fastlane build_framework_for_testing
      - name: Cache DerivedData
        uses: actions/cache@v3
        with:
          path: output/DerivedData
          key: ${{ runner.os }}-framework_derived_data-run_id_${{ github.run_id }}

  build_demo_for_testing:
    runs-on: macos-latest
    name: build_demo_for_testing
    needs: build_framework_for_testing
    strategy:
      fail-fast: false
    steps:
      - name: Cancel previous jobs
        uses: styfle/cancel-workflow-action@0.6.0
        with:
          access_token: ${{ github.token }}
      - name: Git - Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          ruby-version: 2.6
      - run: bundle install
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: "12.5.1"
      - name: Cache DerivedData
        uses: actions/cache@v3
        with:
          path: output/DerivedData
          key: ${{ runner.os }}-framework_derived_data-run_id_${{ github.run_id }}
      - name: Build demo
        run: bundle exec fastlane build_demo_for_testing
      - name: Cache DerivedData
        uses: actions/cache@v3
        with:
          path: output/DerivedData
          key: ${{ runner.os }}-demo_derived_data-run_id_${{ github.run_id }}

  ui_tests:
    runs-on: macos-latest
    name: ui_tests
    needs: build_demo_for_testing
    strategy:
      fail-fast: false
      matrix:
        testplan: ["TestKitDemoUITestsPlan0", "TestKitDemoUITestsPlan1"]
    steps:
      - name: Cancel previous jobs
        uses: styfle/cancel-workflow-action@0.6.0
        with:
          access_token: ${{ github.token }}
      - name: Git - Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          ruby-version: 2.6
      - run: bundle install
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: "12.5.1"
      - name: Cache DerivedData
        uses: actions/cache@v3
        with:
          path: output/DerivedData
          key: ${{ runner.os }}-demo_derived_data-run_id_${{ github.run_id }}
      - name: ${{ matrix.testplan }}
        run: bundle exec fastlane demo_ui_test_plan testplan:${{ matrix.testplan }}
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action/composite@v2
        if: always()
        with:
          junit_files: |
           output/tests/*.html
           output/xcov/report.html
           "output/tests/*.xcresult"