name: pr_workflow

on:
  pull_request:
    branches:
      - main
      
jobs:
  build_framework:
    runs-on: macos-latest
    name: build_framework
    strategy:
      fail-fast: false
    steps:
      - name: Cancel previous jobs
        uses: styfle/cancel-workflow-action@0.6.0
        with:
          access_token: ${{ github.token }}
      - name: Git - Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          ruby-version: 2.6
      - run: bundle install
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '12.5.1'
      - name: Clean fastlane output
        run: bundle exec fastlane clean
      - name: Build
        run: bundle exec fastlane build_framework
      - name: Cache DerivedData
        uses: actions/cache@v3
        with:
          path: output/build/DerivedData
          key: derived_data
          restore-keys: ${{ runner.os }}-derived_data

  build_demo:
    runs-on: macos-latest
    name: build_demo
    needs: build_framework
    strategy:
      fail-fast: false
    steps:
      - name: Cancel previous jobs
        uses: styfle/cancel-workflow-action@0.6.0
        with:
          access_token: ${{ github.token }}
      - name: Git - Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          ruby-version: 2.6
      - run: bundle install
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '12.5.1'
      - name: Cache DerivedData
        uses: actions/cache@v3
        with:
          path: output/build/DerivedData
      - name: Build demo
        run: bundle exec fastlane build_demo scheme:TestKitDemo

  ui_tests:
    runs-on: macos-latest
    name: ui_tests
    needs: build_demo
    strategy:
      fail-fast: false
      matrix:
        testplan: ["TestKitDemoUITests", "TestKitDemoUITestsPlan1"]
    steps:
      - name: Cancel previous jobs
        uses: styfle/cancel-workflow-action@0.6.0
        with:
          access_token: ${{ github.token }}
      - name: Git - Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          ruby-version: 2.6
      - run: bundle install
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '12.5.1'
      - name: Cache DerivedData
        uses: actions/cache@v3
        with:
          path: output/build/DerivedData
          key: derived_data
          restore-keys: ${{ runner.os }}-derived_data
      - name: ${{ matrix.testplan }}
        run: bundle exec fastlane ui_tests scheme:TestKitDemoUITests testplan:${{ matrix.testplan }}
      - uses: kishikawakatsumi/xcresulttool@v1.4.0
        with:
          path: ./output/tests/${{ matrix.testplan }}.xcresult
        if: success() || failure()
