name: Pull requeston

on:
  pull_request:
    branches:
      - main
      
jobs:
  pr-pipeline:
    runs-on: macos-latest
    name: XCode ${{ matrix.xcode }}
    strategy:
      fail-fast: false #if 'true' then one failed job cancels all jobs remaining
      matrix:
        xcode: ['13.2.1', '12.5.1']
    steps:
      - name: Cancel previous jobs
        uses: styfle/cancel-workflow-action@0.6.0
        with:
          access_token: ${{ github.token }}
      - name: Git - Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          ruby-version: 2.6
      - run: bundle install
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '${{ matrix.xcode }}'
      - name: Build
        run: bundle exec fastlane build scheme:TestKit
      - name: Test plan
        run: bundle exec fastlane ui_tests scheme:TestKitDemoUITests testplan:'TestKitDemoUITests'
      - name: Test plan
        run: bundle exec fastlane ui_tests scheme:TestKitDemoUITests testplan:'TestKitDemoUITestsPlan1'
      - uses: kishikawakatsumi/xcresulttool@v1.4.0
        with:
          path: /Users/runner/work/TestKit/TestKit/tests_output/TestKitDemoUITests.xcresult 
        if: success() || failure()
